# Generated by Django 3.1.1 on 2020-09-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_auto_20200906_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='place',
            new_name='position',
        ),
    ]
